
server:
  port: 8091

spring:
  datasource:
     url: jdbc:mysql://52.188.186.190:3306/ojas_obs
     username: dbubora
     password: Ojas-1525
     driver-class-name: com.mysql.jdbc.Driver
     hikari : 
      connection-timeout : 500
      maximum-pool-size : 2 
 #  url: jdbc:mysql://localhost:3306/ojas_obs?autoReconnect=true&useSSL=false
 #  username: root
 #  password: sai@1234
 #  driver-class-name: com.mysql.cj.jdbc.Driver
 
 



