server:
   port: 8016
   
spring:
 datasource:
    url: jdbc:mysql://52.188.186.190:3306/ojas_obs
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2 
#   url: jdbc:mysql://localhost:3306/ojas_obs?autoReconnect=true&useSSL=false
#   username: root
#   password: root
#   driver-class-name: com.mysql.cj.jdbc.Driver
