
server:
   port: 8087
   
spring:
 datasource:


    url: jdbc:mysql://52.188.186.190:3306/ojas_obs   
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver 
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2 

#server:
#   port: 8015
#   
#spring:
# datasource:
#   url: jdbc:mysql://localhost:3306/employeebu
#   driver-class-name: com.mysql.jdbc.Driver
#   username: root
#   password: root

 

